---
title: "writing functions"
author: "Duzhi Zhao"
date: "10/24/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(1)

```

```{r}
x = rnorm(25, mean = 5, sd = 3)
x - mean(x) / sd(x)
y = rnorm(25, mean = 1, sd = 0.5)
```

## Single output: z-score function
```{r}
z_score = function(x){
  (x - mean(x)) / sd(x)
}

z_score(x = y)

```

```{r}
z_score = function(x){
  if (!is.numeric(x)) {
    stop("Argument should be numeric")
  } else if (length(x) == 1) {
    stop("z-scores cannot be computed for length 1 vectors")
  }
  z = (x - mean(x)) / sd(x)
  z
}

z_score(x = y)
```

## multiple outputs
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  list(
    mean_x = mean(x),
    sd_x = sd(x),
    z_score = (x - mean(x)) / sd(x)
  )
}
```

```{r}
mean_and_sd(x = y)
```

## Multiple inputs
```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)

beta0_hat = coef(ls_fit)[1] # extract intercept from Is_fit
beta1_hat = coef(ls_fit)[2] # extract slope from Is_fit

sim_data %>% 
  ggplot(aes(x = x, y = y)) + geom_point()


```

```{r}
sim_regression = function(n, beta0, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_regression(3000, 17, -3)
```

## Scraping amazon
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

```{r}
read_page_reviews = function(url){
  dynamite_html = read_html(url)
  
  review_titles = dynamite_html %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = dynamite_html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text()
  
  review_text = dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text()
  
  reviews = tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```

```{r}
read_page_reviews("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=3")
```

